//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Tab
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Состав.
    /// </summary>
    // *** Start programmer edit section *** (Состав CustomAttributes)

    // *** End programmer edit section *** (Состав CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("СоставE", new string[] {
            "Сотрудник as \'Сотрудник\'",
            "Сотрудник.фамилия as \'Фамилия\'",
            "Должность as \'Должность\'",
            "Должность.Код as \'Код\'"}, Hidden=new string[] {
            "Сотрудник.фамилия",
            "Должность.Код"})]
    [MasterViewDefineAttribute("СоставE", "Сотрудник", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "фамилия")]
    [MasterViewDefineAttribute("СоставE", "Должность", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Код")]
    public class Состав : ICSSoft.STORMNET.DataObject
    {
        
        private IIS.Tab.Сотрудник fСотрудник;
        
        private IIS.Tab.Должность fДолжность;
        
        private IIS.Tab.Бригада fБригада;
        
        // *** Start programmer edit section *** (Состав CustomMembers)

        // *** End programmer edit section *** (Состав CustomMembers)

        
        /// <summary>
        /// Состав.
        /// </summary>
        // *** Start programmer edit section *** (Состав.Должность CustomAttributes)

        // *** End programmer edit section *** (Состав.Должность CustomAttributes)
        [PropertyStorage(new string[] {
                "Должность"})]
        [NotNull()]
        public virtual IIS.Tab.Должность Должность
        {
            get
            {
                // *** Start programmer edit section *** (Состав.Должность Get start)

                // *** End programmer edit section *** (Состав.Должность Get start)
                IIS.Tab.Должность result = this.fДолжность;
                // *** Start programmer edit section *** (Состав.Должность Get end)

                // *** End programmer edit section *** (Состав.Должность Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Состав.Должность Set start)

                // *** End programmer edit section *** (Состав.Должность Set start)
                this.fДолжность = value;
                // *** Start programmer edit section *** (Состав.Должность Set end)

                // *** End programmer edit section *** (Состав.Должность Set end)
            }
        }
        
        /// <summary>
        /// Состав.
        /// </summary>
        // *** Start programmer edit section *** (Состав.Сотрудник CustomAttributes)

        // *** End programmer edit section *** (Состав.Сотрудник CustomAttributes)
        [PropertyStorage(new string[] {
                "Сотрудник"})]
        [NotNull()]
        public virtual IIS.Tab.Сотрудник Сотрудник
        {
            get
            {
                // *** Start programmer edit section *** (Состав.Сотрудник Get start)

                // *** End programmer edit section *** (Состав.Сотрудник Get start)
                IIS.Tab.Сотрудник result = this.fСотрудник;
                // *** Start programmer edit section *** (Состав.Сотрудник Get end)

                // *** End programmer edit section *** (Состав.Сотрудник Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Состав.Сотрудник Set start)

                // *** End programmer edit section *** (Состав.Сотрудник Set start)
                this.fСотрудник = value;
                // *** Start programmer edit section *** (Состав.Сотрудник Set end)

                // *** End programmer edit section *** (Состав.Сотрудник Set end)
            }
        }
        
        /// <summary>
        /// мастеровая ссылка на шапку IIS.Tab.Бригада.
        /// </summary>
        // *** Start programmer edit section *** (Состав.Бригада CustomAttributes)

        // *** End programmer edit section *** (Состав.Бригада CustomAttributes)
        [Agregator()]
        [NotNull()]
        [PropertyStorage(new string[] {
                "Бригада"})]
        public virtual IIS.Tab.Бригада Бригада
        {
            get
            {
                // *** Start programmer edit section *** (Состав.Бригада Get start)

                // *** End programmer edit section *** (Состав.Бригада Get start)
                IIS.Tab.Бригада result = this.fБригада;
                // *** Start programmer edit section *** (Состав.Бригада Get end)

                // *** End programmer edit section *** (Состав.Бригада Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Состав.Бригада Set start)

                // *** End programmer edit section *** (Состав.Бригада Set start)
                this.fБригада = value;
                // *** Start programmer edit section *** (Состав.Бригада Set end)

                // *** End programmer edit section *** (Состав.Бригада Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "СоставE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View СоставE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("СоставE", typeof(IIS.Tab.Состав));
                }
            }
        }
    }
    
    /// <summary>
    /// Detail array of Состав.
    /// </summary>
    // *** Start programmer edit section *** (DetailArrayDetailArrayOfСостав CustomAttributes)

    // *** End programmer edit section *** (DetailArrayDetailArrayOfСостав CustomAttributes)
    public class DetailArrayOfСостав : ICSSoft.STORMNET.DetailArray
    {
        
        // *** Start programmer edit section *** (IIS.Tab.DetailArrayOfСостав members)

        // *** End programmer edit section *** (IIS.Tab.DetailArrayOfСостав members)

        
        /// <summary>
        /// Construct detail array.
        /// </summary>
        /// <summary>
        /// Returns object with type Состав by index.
        /// </summary>
        /// <summary>
        /// Adds object with type Состав.
        /// </summary>
        public DetailArrayOfСостав(IIS.Tab.Бригада fБригада) : 
                base(typeof(Состав), ((ICSSoft.STORMNET.DataObject)(fБригада)))
        {
        }
        
        public IIS.Tab.Состав this[int index]
        {
            get
            {
                return ((IIS.Tab.Состав)(this.ItemByIndex(index)));
            }
        }
        
        public virtual void Add(IIS.Tab.Состав dataobject)
        {
            this.AddObject(((ICSSoft.STORMNET.DataObject)(dataobject)));
        }
    }
}
