//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Tab
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Сотрудник.
    /// </summary>
    // *** Start programmer edit section *** (Сотрудник CustomAttributes)

    // *** End programmer edit section *** (Сотрудник CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("СотрудникE", new string[] {
            "фамилия as \'Фамилия\'",
            "отчество as \'Отчество\'",
            "имя as \'Имя\'",
            "табном as \'Табном\'"})]
    [View("СотрудникL", new string[] {
            "фамилия as \'Фамилия\'",
            "отчество as \'Отчество\'",
            "имя as \'Имя\'",
            "табном as \'Табном\'"})]
    public class Сотрудник : ICSSoft.STORMNET.DataObject
    {
        
        private string fфамилия;
        
        private string fотчество;
        
        private string fимя;
        
        private string fтабном;
        
        // *** Start programmer edit section *** (Сотрудник CustomMembers)

        // *** End programmer edit section *** (Сотрудник CustomMembers)

        
        /// <summary>
        /// имя.
        /// </summary>
        // *** Start programmer edit section *** (Сотрудник.имя CustomAttributes)

        // *** End programmer edit section *** (Сотрудник.имя CustomAttributes)
        [StrLen(255)]
        public virtual string имя
        {
            get
            {
                // *** Start programmer edit section *** (Сотрудник.имя Get start)

                // *** End programmer edit section *** (Сотрудник.имя Get start)
                string result = this.fимя;
                // *** Start programmer edit section *** (Сотрудник.имя Get end)

                // *** End programmer edit section *** (Сотрудник.имя Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Сотрудник.имя Set start)

                // *** End programmer edit section *** (Сотрудник.имя Set start)
                this.fимя = value;
                // *** Start programmer edit section *** (Сотрудник.имя Set end)

                // *** End programmer edit section *** (Сотрудник.имя Set end)
            }
        }
        
        /// <summary>
        /// отчество.
        /// </summary>
        // *** Start programmer edit section *** (Сотрудник.отчество CustomAttributes)

        // *** End programmer edit section *** (Сотрудник.отчество CustomAttributes)
        [StrLen(255)]
        public virtual string отчество
        {
            get
            {
                // *** Start programmer edit section *** (Сотрудник.отчество Get start)

                // *** End programmer edit section *** (Сотрудник.отчество Get start)
                string result = this.fотчество;
                // *** Start programmer edit section *** (Сотрудник.отчество Get end)

                // *** End programmer edit section *** (Сотрудник.отчество Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Сотрудник.отчество Set start)

                // *** End programmer edit section *** (Сотрудник.отчество Set start)
                this.fотчество = value;
                // *** Start programmer edit section *** (Сотрудник.отчество Set end)

                // *** End programmer edit section *** (Сотрудник.отчество Set end)
            }
        }
        
        /// <summary>
        /// табном.
        /// </summary>
        // *** Start programmer edit section *** (Сотрудник.табном CustomAttributes)

        // *** End programmer edit section *** (Сотрудник.табном CustomAttributes)
        [StrLen(255)]
        public virtual string табном
        {
            get
            {
                // *** Start programmer edit section *** (Сотрудник.табном Get start)

                // *** End programmer edit section *** (Сотрудник.табном Get start)
                string result = this.fтабном;
                // *** Start programmer edit section *** (Сотрудник.табном Get end)

                // *** End programmer edit section *** (Сотрудник.табном Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Сотрудник.табном Set start)

                // *** End programmer edit section *** (Сотрудник.табном Set start)
                this.fтабном = value;
                // *** Start programmer edit section *** (Сотрудник.табном Set end)

                // *** End programmer edit section *** (Сотрудник.табном Set end)
            }
        }
        
        /// <summary>
        /// фамилия.
        /// </summary>
        // *** Start programmer edit section *** (Сотрудник.фамилия CustomAttributes)

        // *** End programmer edit section *** (Сотрудник.фамилия CustomAttributes)
        [StrLen(255)]
        public virtual string фамилия
        {
            get
            {
                // *** Start programmer edit section *** (Сотрудник.фамилия Get start)

                // *** End programmer edit section *** (Сотрудник.фамилия Get start)
                string result = this.fфамилия;
                // *** Start programmer edit section *** (Сотрудник.фамилия Get end)

                // *** End programmer edit section *** (Сотрудник.фамилия Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Сотрудник.фамилия Set start)

                // *** End programmer edit section *** (Сотрудник.фамилия Set start)
                this.fфамилия = value;
                // *** Start programmer edit section *** (Сотрудник.фамилия Set end)

                // *** End programmer edit section *** (Сотрудник.фамилия Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "СотрудникE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View СотрудникE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("СотрудникE", typeof(IIS.Tab.Сотрудник));
                }
            }
            
            /// <summary>
            /// "СотрудникL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View СотрудникL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("СотрудникL", typeof(IIS.Tab.Сотрудник));
                }
            }
        }
    }
}
